src/TestMaker/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('accounts.urls',namespace='accounts')),
    url(r'compile/',include("oncomp.urls",namespace='oncomp')),
    url(r'test/',include('tests.urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.conf.urls import url,static
from django.conf import settings
from . import views
app_name='accounts'
urlpatterns=[
    url(r'^$',views.Indexpage.as_view(),name="index"),
    url(r'^register/$', views.Registerpage.as_view(), name="register"),
    url(r'^profile/(?P<slug>[\w-]+)/$',views.profileview,name="profile"),
    url(r'^home/',views.Homepage.as_view(),name="home"),
    url(r'^logout/',views.logoutview,name="logout"),
    url(r'^validate_username',views.validate_username,name="validateusername"),

]

src/oncomp/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
    url(r'^createtestview/',views.createtestview.as_view(),name="test"),
    url(r'^ctest/(?P<ctest_id>[0-9]+)/$',views.ctest.as_view(),name="ctest"),
    url(r'^ctestexpire/',views.ctestexpire,name="ctestexpire"),
    url(r'^cupdatetime/',views.cupdatetime,name="cupdatetime"),
]

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.conf import settings
from django.db.models.signals import post_save
class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given emailand password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),

        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,

        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'


    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
class requests(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    isaccepted=models.BooleanField(default=False)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    admissionno = models.CharField(max_length=7)
    choice = (
        ('PC', 'Placement_Cell'),
        ('TC', 'Training_Cell'),
        ('ST', 'Student'),
    )
    image= models.FileField(default='user.png')
    status = models.CharField(max_length=2, choices=choice, default='ST')
    standard=models.CharField(max_length=5,default="CSA")
    name=models.CharField(max_length=14,unique=True)
    slug=models.SlugField(max_length=14)
    def _str_(self):
        return self.user.email

    def __unicode__(self):
        return self.user.email


def post_save_user_model_reciever(sender, instance, created, *args, **kwargs):
    if created:
        try:
            Profile.objects.create(MyUser=instance)
        except:
            pass


post_save.connect(post_save_user_model_reciever, sender=settings.AUTH_USER_MODEL)

src/accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, login ,logout,get_user_model
from .models import Profile
from tests import models
User=get_user_model()
class LoginForm(forms.Form):
    email=forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    def clean(self):
        email=self.cleaned_data.get("email")
        password=self.cleaned_data.get("password")
        user=authenticate(email=email,password=password)
        if not user:
            raise forms.ValidationError("THis user does not exist")
        if not user.check_password(password):
            raise forms.ValidationError("Incorrect Password")
    
        return super(LoginForm,self).clean()

class ProfileForm(forms.ModelForm):
    admissionno=forms.CharField(max_length=7,widget=forms.TextInput(attrs={"class":"form-control"}))
    name=forms.CharField(max_length=14,widget=forms.TextInput(attrs={"class":"form-control"}))
    image=forms.FileField(widget=forms.FileInput(attrs={"type":"file" ,"accept":"image/*"," onchange":"loadFile(event)"}))
    class Meta:
        model= Profile
        fields=['admissionno','name','image','status']

src/accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponseRedirect,HttpResponse
from django.views import View
from accounts.admin import UserCreationForm
from django.contrib.auth import authenticate, login ,logout
from .forms import ProfileForm
from accounts.forms import LoginForm
from django.contrib.auth import get_user_model
from .models import Profile,requests
from django.template.defaultfilters import slugify
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from tests.models import Apt_Test
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from . import models
from django.urls import reverse ,reverse_lazy
user =get_user_model()

# Create your views here.
class Indexpage(View):
    template_name='index.html'
    def get(self, request, *args):
        form=LoginForm()
        return render(request,self.template_name,{"form":form})
    def post(self,request, *args):
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('/home/')
        return render(request, self.template_name, {"form": form})
class Registerpage(View):
    template_name='register2.html'
    def get(self, request, *args):

        form=UserCreationForm()
        profile=ProfileForm()
        context={
            "form":form,
            "profile":profile,
        }
        return render(request,self.template_name,context)

    def post(self, request, *args):
        form = UserCreationForm(request.POST)
        profile = ProfileForm(request.POST,request.FILES)
        context = {
            "form": form,
            "profile":profile,

        }
        if form.is_valid() and profile.is_valid():
            user = form.save()
            pro= profile.save(commit=False)

            pro.user=user
            if pro.status!='ST':
                requests.objects.create(user=user)
            pro.slug=slugify(pro.name)

            pro.save()
            if pro is not None:
                login(request,user)
                return redirect('/home/')

        return render(request, self.template_name, context)
class Homepage(View):
    template_name='home.html'
    tctemplate='tcpc.html'
    adminpage="admin.html"
    def get(self,request,*args):

        if not request.user.is_authenticated:
            return redirect(reverse("accounts:index"))
        # if user.is_superuser:
        #
        #     return render(request,self.adminpage,{})
        p=Profile.objects.get(user=request.user)
        if p.status != 'ST':
            req=requests.objects.get(user=request.user)

            if req.isaccepted:

                return render(request,self.tctemplate,{"profile":p,
                                                   "homelink":"active"})
            else:
                return HttpResponse("Contact tcadmin to get verified ")
        #paginatior code these contacts are really tests im too lazy to change the names
        contact_list = Apt_Test.objects.all()
        paginator = Paginator(contact_list, 5)
        page = request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            contacts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            contacts = paginator.page(paginator.num_pages)

        return render(request,self.template_name,{"profile":p,'contacts': contacts})


def logoutview(request):
    logout(request)
    return redirect('/')


@login_required(redirect_field_name='redirecting',login_url='')

def profileview(request,slug):
    p = Profile.objects.get(slug=slug)
    return render(request,'profile.html',{"profile":p,"profilelink":"active"})



def validate_username(request):
    username = request.GET.get('name', None)
    data = {
        'is_taken': Profile.objects.filter(name__iexact=username).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'A user with this username already exists.'
    return JsonResponse(data)

src/accounts/templates/base.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Frontpage{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.css' %}" crossorigin="anonymous">
	<link rel="stylesheet" href='{% static "css/reg.css"%}'>

	<link rel='stylesheet' href='{% static "css/style.css"%}'>

</head>
</head>
	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}

	{% block body %}
	{% endblock %}

	<footer> <script src="{% static  'bower_components/jquery/dist/jquery.js' %}"></script>
		<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.js' %}" crossorigin="anonymous"></script>
		<script src="{% static 'bower_components/jquery.countdown/dist/jquery.countdown.js' %}																			"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
       <script src="{% static 'js/main.js' %}"></script>
		<script src="{% static 'js/reg.js' %}"></script>

		<script src="{% static '/ace-builds/src/ace.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static '/ace-builds/demo/kitchen-sink/demo.js' %}"></script>

		<script type="text/javascript">
			$(function(){
			{% block jquery %}{% endblock %}
			});
		</script>
	</footer>

</html>

src/accounts/templates/createtest.html
{% extends 'base.html' %}
{% block body %}
{% load crispy_forms_tags %}

<a href="{% url 'accounts:logout'%}">Logout</a>
<h1>Create Test</h1>
.jumbotron.col-md-5.col-md-offset
    <form action="." method="post">
    {{tform | crispy}}
        <input type="submit">
    </form>


{% endblock%}

src/accounts/templates/home.html
{% extends 'base.html' %}
{% block title %}
Home
{%endblock%}
{% block body %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Questionnaire</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home<span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'accounts:profile' profile.slug %}">Profile</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class="col-md-3 col-md-offset-1  side">
    <img src="{{profile.image.url }}" alt="" class="img-responsive img-circle img-thumbnail pimage">
    <h2><span class="glyphicon glyphicon-user" aria-hidden="true">{{profile.name}}</span></h2>
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation"><a href="#">Results</a></li>
        <li role="presentation"><a href="#">Ranks</a></li>
    </ul>


</div>

<div class="col-md-6 col-md-offset-1 jumbotron rightside ">


<!--these contacts are really tests im too lazy to change the names-->
    <div class="testlinks">
    {% for contact in contacts %}
     <div class="panel panel-default">
      <div class="panel-body">
          <a href="{% url 'test' contact.id %}">{{ contact.name}}</a>

      </div>
    </div>
    {% endfor %}
    </div>
    <div class="pagination">
    <span class="step-links">
        {% if contacts.has_previous %}
            <a href="?page={{ contacts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
        </span>

        {% if contacts.has_next %}
            <a href="?page={{ contacts.next_page_number }}">next</a>
        {% endif %}
    </span>
    </div>



</div>

{% endblock %}

src/accounts/templates/index.html
{% extends 'base.html' %}
{% block title %}
Quiz
{% endblock %}
{% block body %}

<body class="frontpage">
	<div class="col-md-12 main visible-lg visible-md">




		<div class="col-md-7 col-md-offset-1 jumbotron header">
			<h1 class="pageheader brighten">
				let your minds<br>be quizzed
			</h1>
			<br>
		</div>
		

	</div>
	<div class="col-md-12 jumbotron login">

		




	
		<div class="aa col-md-6 ">
				<div class="a b ">
				<img  src="https://upload.wikimedia.org/wikipedia/en/thumb/6/64/Meclogo.jpg/220px-Meclogo.jpg">
				</div>
				<h2 class="cap">Lets make MEC shine</h2>
		</div>
		
		<div class="col-md-4 col-md-offset-1 loginform">
			<form method="post" action=".">{% csrf_token %}
				<div class="col-md-12  l">
				<h3>Account <span class="label label-primary">Login</span></h3>
				</div>




				{{ form.non_field_errors }}

			  <div class="form-group">
				  {{ form.email.errors }}
			    <label for="{{ form.email.id_for_label }}">Email address</label>

				{{ form.email }}

			  </div>
			  <div class="form-group">
				  {{ form.password.errors }}
			    <label for="{{ form.password.id_for_label }}">Password</label>

				  {{ form.password }}

			  </div>



			  <button type="submit" class="btn btn-default">Submit</button>
				<br>
				<a href="{% url 'accounts:register' %}">Not Registered?</a>
			</form>
		</div>
	</div>
	
</body>
{% endblock %}

src/accounts/templates/profile.html
  {% extends 'base.html' %}
{% block body %}


  <div class="jumbotron col-md-7 col-md-offset-2">

      <ul class="list-group">
          <img src="{{profile.image.url}}" alt="">
      <li class="list-group-item"> {{profile.name}}</li>
      <li class="list-group-item"> {{profile.admissionno}}</li>
      <li class="list-group-item"> {{profile.status}}</li>
    </ul>

      </div>
  {% endblock %}

src/accounts/templates/register.html
  {% extends 'base.html' %}
  {% block title %} Register {% endblock %}
{% block body %}


<div class="jumbotron col-md-5 col-md-offset-3 registration ">
    <label><h2>Registion Form</h2></label>
    <form action="." method="post" enctype="multipart/form-data" data-validate-username-url="{% url 'accounts:validateusername' %}" >{% csrf_token %}
             {% if form.form.non_field_errors or profile.name.errors  %}
            <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
                 {{ profile.name.errors }}
            </div>
            {% endif %}
           <div class="profile-group hidden errors">
               Heloo
              </div>


               <div class="profile-group">

                <label for="{{ profile.status.id_for_label }}">UserName</label>

              {{ profile.name }}

              </div>

			  <div class="form-group">
				  {{ form.email.errors }}
			    <label for="{{ form.email.id_for_label }}">Email address</label>

				{{ form.email }}

			  </div>
			  <div class="form-group">
				  {{ form.password1.errors }}
			    <label for="{{ form.password1.id_for_label }}">Password</label>

				  {{ form.password1 }}

			  </div>

                <div class="form-group">
				  {{ form.password2.errors }}
			    <label for="{{ form.password2.id_for_label }}">Confirm Password</label>

				  {{ form.password2 }}

			  </div>

            {{ profile.non_field_errors }}

              <div class="profile-group">
                  {{ profile.admissionno.errors }}
                <label for="{{ profile.admissionno.id_for_label }}">Admissionno </label>
                  {{ profile.admissionno }}

              </div>

              <div class="profile-group">
                  {{ profile.image.errors }}
                <label for="{{ profile.image.id_for_label }}">image </label>
                  {{ profile.image }}

              </div>




              <div class="profile-group">
                  {{ profile.status.errors }}
                <label for="{{ profile.status.id_for_label }}">Status</label>

                  {{ profile.status }}

              </div>





        <input type="submit">
    </form>

</div>

{% endblock %}

src/accounts/templates/register2.html
  {% extends 'base.html' %}
  {% block title %} Register {% endblock %}
{% block body %}
  <div class ="registration">
    <div class="container">
        <div class="lbg">
        </div>
        <div class="lbg2">
        </div>
        <div class="lO">
        </div>
        <div class="lC">
            <h1>Sign Up</h1>
            <h3>We'll help you build a better career.</h3>
            <h5>Lets take the first step.</h5>

            <h1>TestFORCE</h1>
        </div>
        <form action="." method="post" enctype="multipart/form-data" data-validate-username-url="{% url 'accounts:validateusername' %}" >{% csrf_token %}
             {% if form.form.non_field_errors or profile.name.errors  %}
            <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
                 {{ profile.name.errors }}

            </div>
            {% endif %}
           <div class="profile-group hidden errors">

              </div>
            <div class="rightSec" id="first">
                <ul>
                    <li>
                        <label>
                            Full name
                        </label>
                        {{ profile.name }}
                    </li>

                    <li>
                         {{ form.email.errors }}
                        <label>
                            Official email
                        </label>
                        {{ form.email }}
                    <li>

                </ul>
                <div class="nav_link">
                    <a href="#" id="continue" style="float:right;">Continue</a>
                </div>
            </div>

            <!-- Section 2 -->


            <div class="rightSec" id="second" style="display:none">

               <li>{{ profile.admissionno.errors }}
                     <label>
                        Admission Number
                     </label>
                      {{ profile.admissionno }}
                </li>
                     {{ form.password1.errors }}
                         <label>
                            Password
                        </label>
                          {{ form.password1 }}
                    </li>
                    <li>
                         {{ form.password2.errors }}
                        <label>
                            Re-type Password
                        </label>
                         {{ form.password2 }}
                    </li>
                <div class="nav_link">
                    <a href="#" id="prev">Previous</a>
                    <a href="#" id="continue2" style="float:right;">Continue</a>
                </div>
            </div>





            <!-- Section 3 -->

            <div class="rightSec" id="third" style="display:none">
                <ul>
                     {{ profile.non_field_errors }}
                   <li>
                          {{ profile.status.errors }}
                        <label>
                            Status
                        </label>
                          {{ profile.status }}
                    </li>
                    <li>  {{ profile.image.errors }}
                         <label>
                            Upload Profile Picture
                         </label>
                              {{ profile.image }}

                          <br>
                          <img id="output" width="200" />
                    </li>

                </ul>
                <div class="nav_link">
                    <a href="#" id="prev2">Previous</a>
                    <a href="#" id="continue3" style="float:right;">Continue</a>
                </div>
            </div>



           <!-- Section 4 -->


            <div class="rightSec" id="fourth" style="display:none">
                <div class="ty">
                    <h1>Thank you!</h1>
                    <h3>To finish your registeration, please click the button below.</h3>
                    <h5>Be patient while we process your application.</h5>
                    <button type="submit" value="submit">Finish</button>
                </div>
                <div class="nav_link">
                    <a href="#" id="prev3">Previous</a>
                </div>
            </div>
        </form>
    </div>
        <div class="progress_state">
            <div class="dot" id="dot1"></div>
            <div class="dot" id="dot2"></div>
            <div class="dot" id="dot3"></div>
            <div class="dot" id="dot4"></div>
        </div>
{% endblock %}

src/accounts/templates/tcpc.html
{% extends 'base.html' %}
{% block title %}
Home
{%endblock%}
{% block body %}

{% include 'header.html' %}
<div class="col-md-3 col-md-offset-1  side">
    <img src="{{profile.image.url }}" alt="" class="img-responsive img-circle img-thumbnail pimage">
    <h2><span class="glyphicon glyphicon-user" aria-hidden="true">{{profile.name}}</span></h2>
    <ul class="nav nav-pills nav-stacked">
        <li role="presentation"><a href="#">Results</a></li>
        <li role="presentation"><a href="#">Ranks</a></li>
    </ul>


</div>


{% endblock%}