src/TestMaker/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('accounts.urls',namespace='accounts')),
    url(r'compile/',include("oncomp.urls",namespace='oncomp')),
    url(r'test/',include('tests.urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.conf.urls import url,static
from django.conf import settings
from . import views
app_name='accounts'
urlpatterns=[
    url(r'^$',views.Indexpage.as_view(),name="index"),
    url(r'^register/$', views.Registerpage.as_view(), name="register"),
    url(r'^profile/(?P<slug>[\w-]+)/$',views.profileview,name="profile"),
    url(r'^home/',views.Homepage.as_view(),name="home"),
    url(r'^logout/',views.logoutview,name="logout"),
    url(r'^validate_username',views.validate_username,name="validateusername"),

]

src/oncomp/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
    url(r'^createtestview/',views.createtestview.as_view(),name="test"),
    url(r'^ctest/(?P<ctest_id>[0-9]+)/$',views.ctest.as_view(),name="ctest"),
    url(r'^ctestexpire/',views.ctestexpire,name="ctestexpire"),
    url(r'^cupdatetime/',views.cupdatetime,name="cupdatetime"),
]

src/oncomp/models.py
from __future__ import unicode_literals
from tests import models as tmodels
from django.db import models
from django.conf import settings
from datetime import timedelta
class Compilerquestion(models.Model):
    prog = models.TextField(default="")
    pname = models.CharField(max_length=256)
    mark = models.IntegerField(default=0)
    test_id =models.ForeignKey(tmodels.Apt_Test,on_delete=models.CASCADE)
    time=models.DurationField(default="0:30:00")

    def __str__(self):
        return self.pname
class CompilerTestcases(models.Model):
    testcases=models.TextField(max_length=500)
    test_out = models.TextField(max_length=1000, default='No Output')
    question_id = models.ForeignKey(Compilerquestion, on_delete=models.CASCADE)

    def __str__(self):
        return self.test_out


class canswer(models.Model):
    uid=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    tid=models.ForeignKey(tmodels.Apt_Test,on_delete=models.CASCADE)
    qid = models.ForeignKey(Compilerquestion,on_delete=models.CASCADE)
    out=models.TextField(default="")
    program=models.CharField(max_length=15000,default="Enter Your Program Here")
    LANGUAGE_CHOICES = (
        ('python', 'Python'),
        ('java', 'Java'),
        ('c_cpp', 'C++'),
        ('javascript', 'Javascript'),
    )
    language = models.CharField(
        max_length=10,
        choices=LANGUAGE_CHOICES,
        default='python',
    )


    def __str__(self):
        return self.program

class compilertestscore(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    test=models.ForeignKey(tmodels.Apt_Test,on_delete=models.CASCADE)
    score=models.IntegerField(default=0)
    question=models.ForeignKey(Compilerquestion,models.CASCADE)
    itime=models.DurationField(default=timedelta(hours=1))
    def _str_(self):
        return self.user.email

    def __unicode__(self):
        return self.user.email

src/oncomp/forms.py
from django import forms
from django.contrib.auth import authenticate, login ,logout,get_user_model
from . import models
class QuestionForm(forms.ModelForm):
    class Meta:
        model=models.Compilerquestion
        fields=['prog','pname','mark','test_id','time']
class AnswerForm(forms.ModelForm):
    program=forms.CharField(widget=forms.Textarea(attrs={"class":"hidden"}))
    class Meta:
        model=models.canswer
        fields=['program','language']

src/oncomp/views.py
from datetime import timedelta
from django.contrib.auth import get_user_model
from django.http import HttpResponseNotAllowed
from django.shortcuts import render,reverse, HttpResponseRedirect, get_object_or_404,HttpResponse
from django.views import View
from oncomp.compiler import main
from tests import models as tmodels
from . import forms
from . import models

user =get_user_model()
class createtestview(View):
    def get(self,request):
        form=forms.QuestionForm()
        context={
            "form":form,
        }
        return render(request,'compiler.html',context)
class ctest(View):
    template_name='ctest.html'
    result_template_name="cresults.html"
    def get(self,request,ctest_id):
        t=get_object_or_404(tmodels.Apt_Test,pk=(ctest_id))
        form = forms.AnswerForm()
        if (not models.compilertestscore.objects.filter(user=request.user, test=t).exists()) and  t.compilerquestion_set.count() > 0:
            request.session['compilerTestscore_question'] = 1
            if not t.compilerquestion_set.filter(id=request.session['compilerTestscore_question']).exists():
                while (request.session['compilerTestscore_question'] <= t.compilerquestion_set.count() and not (
                t.compilerquestion_set.filter(id=request.session['compilerTestscore_question']).exists())):
                    request.session['compilerTestscore_question'] += 1
            q = t.compilerquestion_set.get(id=request.session['compilerTestscore_question'])
            score = models.compilertestscore.objects.create(user=request.user, test=t,question=q)
            # we can eventually add the times in the respective question but for now this will do
            score.itime = q.time
            # ..
            context = {
                "q": q,
                "ctest": score,
                "ctest_id": ctest_id,
                "form": form
            }
            return render(request, self.template_name, context)
        elif request.session.has_key('compilerTestscore_question') and t.compilerquestion_set.filter(
                pk=request.session['compilerTestscore_question']).exists():
            q = t.compilerquestion_set.get(pk=request.session['compilerTestscore_question'])
            score = models.compilertestscore.objects.get(user=request.user, test=t, question=q)
            context = {
                "q": q,
                "ctest": score,
                "ctest_id": ctest_id,
                "form": form
            }
            return render(request, self.template_name, context)
        else:
            ascore=0
            cscore=0
            if models.compilertestscore.objects.filter(user=request.user, test=t).exists():
                cscore=models.compilertestscore.objects.get(user=request.user, test=t).score
            if tmodels.Testscore.objects.filter(user=request.user,test=t).exists():
                ascore=tmodels.Testscore.objects.get(user=request.user,test=t).score
            context={
            "score":ascore+cscore,
            }
            return render(request,self.result_template_name,context)
    def post(self,request,ctest_id):
        t = get_object_or_404(tmodels.Apt_Test, pk=(ctest_id))
        score = models.compilertestscore.objects.get(user=request.user, test=t)
        form=forms.AnswerForm(request.POST)
        q = t.compilerquestion_set.get(pk=request.session['compilerTestscore_question'])
        if form.is_valid():
            f=form.save(commit=False)
            f.uid=request.user
            f.tid=t
            f.qid=q
            f.save()
            objects = main.process(f.program, q.pname, f.language, q.mark, q.id, request.user)
            mark=objects.core()
            if mark.marks==0:
                return HttpResponseRedirect(reverse("ctest",args=ctest_id))
            score.score+=mark.marks
            score.save()

            request.session['compilerTestscore_question'] += 1
            if t.compilerquestion_set.filter(id=request.session['compilerTestscore_question']).exists():
                q = t.compilerquestion_set.get(id=request.session['compilerTestscore_question'])
            else:
                while (request.session['compilerTestscore_question'] <= t.compilerquestion_set.count() and not (
                t.compilerquestion_set.filter(id=request.session['compilerTestscore_question']).exists())):
                    request.session['compilerTestscore_question'] += 1
            return HttpResponseRedirect(reverse("oncomp:ctest",args=(ctest_id)))
        else:
            request.session['compilerTestscore_question'] += 1
            if t.compilerquestion_set.filter(id=request.session['compilerTestscore_question']).exists():
                q = t.compilerquestion_set.get(id=request.session['compilerTestscore_question'])
            else:
                while (request.session['compilerTestscore_question'] <= t.compilerquestion_set.count() and not (
                        t.compilerquestion_set.filter(id=request.session['compilerTestscore_question']).exists())):
                    request.session['compilerTestscore_question'] += 1
            return HttpResponseRedirect(reverse("oncomp:ctest", args=(ctest_id)))
def ctestexpire(request):
    if not request.is_ajax() or not request.method == 'POST':
        return HttpResponseNotAllowed(['POST'])
    request.session['compilerTestscore_question'] = 0
    return HttpResponse('Sorry expired')
def cupdatetime(request):
    if not request.is_ajax() or not request.method == 'POST':
        return HttpResponseNotAllowed(['POST'])
    test = get_object_or_404(tmodels.Apt_Test, pk=request.POST["ctest_id"])
    score =models.compilertestscore.objects.get(user=request.user, test=test)
    score.itime = timedelta(seconds=int(request.POST["timer"]))
    score.save()
    return HttpResponse("ok")

src/oncomp/templates/compiler.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="jumbotron col-md-5 col-md-offset-2">
    <form action="">
        {{form|crispy}}
        <input type="submit">
    </form>
</div>
{% endblock %}

src/oncomp/templates/cresults.html
{% extends 'base.html' %}
{% block title %}
Results
{%endblock%}
{% block body %}
<div class="jumbotron col-md-5 col-md-offset-2">
    Your Score is {{score}}<br>
    <a href="{% url 'accounts:home' %}">Lets return to home page</a>
</div>
{% endblock %}

src/oncomp/templates/ctest.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div  id="time2" data-time="{{ctest.itime.total_seconds}}"></div>
<div class="panel panel-default col-md-9 col-md-offset-1">
    <div class="panel-heading">{{q}}</div>
    <div class="panel-body">{{q.prog}}</div>
  </div>

<form action="." method="POST">{% csrf_token %}

    <div class=" col-md-3 col-md-offset-1">
        {{ form.errors }}
        {{ form.non_field_errors }}

 <input type="hidden" name="time" id="timervariable2">
      {{form.language|as_crispy_field}}</div>
    <div class="col-md-6 col-md-offset-1 ">
            {{form.program}}

    </div>
    <div class="col-md-3 col-md-offset-5">

        <div id="clock2"></div>
          <button class="btn btn-primary" type="submit" id="progsub">Compile</button>
    </div>

</form>
<div class="col-md-9 col-md-offset-1 ">
  <div id="editor" ></div>
</div>

{% endblock %}
{% block jquery %}
var editor =$('#editor');
var textarea=$('#id_program');
$form =$('#progsub').closest("form")
editor = ace.edit("editor");
editor.setTheme("ace/theme/monokai");
editor.getSession().setValue(textarea.val());
editor.getSession().on('change', function(){
textarea.val(editor.getSession().getValue());
});
editor.setOptions({
  fontFamily: "monospace",
  fontSize: "15pt"
});

$language=$('#id_language');
$language.change(function(){
    editor.getSession().setMode("ace/mode/"+$(this).val());
});

d= new Date();

$time=$("#time2");
$Time=$time.attr("data-time");
$seconds=$Time%60;
$minutes=($Time/60)%60;
$hours=$Time/3600;
$timer=$('#timervariable2');
d.setSeconds(d.getSeconds()+$seconds)
d.setHours(d.getHours()+$hours)
d.setMinutes(d.getMinutes()+$minutes)

$('div#clock2').countdown(d, function(event) {
    var format = '%H:%M:%S';
    $(this).text(event.strftime(format))
        .on('finish.countdown', function(event) {
            //to logout session
            $(this).html('This test is finished !')
             .parent().addClass('disabled');
            $.post("{%url 'oncomp:ctestexpire' %}",{csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value},function(data,status){
               window.location.replace("{% url 'result' ctest_id %}");


            });

});

  });
    $time.countdown(d).on('update.countdown', function(event) {
                $Time=$Time-1;
                $timer.val($Time);
                 $.post("{%url 'oncomp:cupdatetime' %}",{"timer":$timer.val(),"ctest_id":{{ctest_id}},csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value},
                function(data,status){
                 });
               }) .countdown('start');





{% endblock %}

src/oncomp/templates/ctest2.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="panel panel-default col-md-9 col-md-offset-1">
    <div class="panel-heading">{{q}}</div>
    <div class="panel-body">{{q.prog}}</div>
  </div>
<form action="." method="post">{% csrf_token %}
    <div class=" col-md-3 col-md-offset-1">
        {{form|crispy}}

        <button class="btn btn-primary" type="submit" id="progsub">Submit</button>
    </div>

</form>

{% endblock %}
{% block jquery %}
var editor =$('#editor');
var textarea=$('#id_program');
$form =$('#progsub').closest("form")
editor = ace.edit("editor");
editor.setTheme("ace/theme/monokai");
editor.getSession().setValue(textarea.val());
editor.getSession().on('change', function(){
textarea.val(editor.getSession().getValue());
});
$language=$('#id_language');
$language.change(function(){
    editor.getSession().setMode("ace/mode/"+$(this).val());
});

{% endblock %}